//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MixTillYouMakeIt : DbContext
    {
        public MixTillYouMakeIt()
            : base("name=MixTillYouMakeIt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminRecord> AdminRecords { get; set; }
        public virtual DbSet<CustomerTB> CustomerTBs { get; set; }
        public virtual DbSet<OrderTB> OrderTBs { get; set; }
        public virtual DbSet<ProductTB> ProductTBs { get; set; }
        public virtual DbSet<TransactionTB> TransactionTBs { get; set; }
    }
}
