//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTB
    {
        public int Product_ID { get; set; }
        public string Product_Category { get; set; }
        public string Product_Name { get; set; }
        public int Product_Price { get; set; }
        public string imageUrlString { get; set; }
    }
}
