//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionTB()
        {
            this.AdminRecords = new HashSet<AdminRecord>();
        }
    
        public int TransactionID { get; set; }
        public Nullable<int> Total_Transaction { get; set; }
        public Nullable<int> Payement_Amount { get; set; }
        public Nullable<int> Change { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminRecord> AdminRecords { get; set; }
    }
}
